
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: abdozayan
  host: localhost

development:
  <<: *default
  database: App_backend_dev

test:
  <<: *default
  database: App_backend_test

production:
  url: <%= ENV['DATABASE_URL'] %>
