Greeting.create(greeting: "Welcome to my website!")
Greeting.create(greeting: "Hey there!")
Greeting.create(greeting: "Have a good Day")
Greeting.create(greeting: "Good Day!")
Greeting.create(greeting: "Hello there")