Greeting.create(message: "Welcome to my website!")
Greeting.create(message: "Hey there!")
Greeting.create(message: "Have a good Day")
Greeting.create(message: "Good Day!")
Greeting.create(message: "Hello there")